### ISSUE TITLE
Address upstream issues

### ISSUE THREAD

**Issue by aaliddell** [rules-proto-grpc/rules_proto_grpc#4]
Tracking resolution of upstream issues

- [x] stackb/rules_proto#54: Covered by `python_dashes` test workspace
- [x] stackb/rules_proto#56: No longer relevant
- [x] stackb/rules_proto#63: Covered by `proto_source_root` test workspace
- [x] stackb/rules_proto#64: Covered by `strip_import_prefix` test workspace
- [ ] stackb/rules_proto#65: Not tested
- [ ] stackb/rules_proto#67: Not tested
- [ ] stackb/rules_proto#68: Not tested
- [x] stackb/rules_proto#83: Resolved
- [x] stackb/rules_proto#101: Working
- [x] stackb/rules_proto#103: Resolved
- [x] stackb/rules_proto#105: `python_version` added
- [x] stackb/rules_proto#106: Resolved as part of move to aspects
- [x] stackb/rules_proto#107: Dart not supported
- [ ] stackb/rules_proto#108: Pending gRPC release
- [x] stackb/rules_proto#109: Resolved. Well known are excluded
- [ ] stackb/rules_proto#110: Not tested
- [ ] stackb/rules_proto#111: Not tested
- [x] stackb/rules_proto#112: Resolved, files merged
- [x] stackb/rules_proto#113: Covered by `shared_proto` test workspace
- [x] stackb/rules_proto#114: Resolved, dependency updated
- [x] stackb/rules_proto#116: Resolved, discussed in https://github.com/rules-proto-grpc/rules_proto_grpc/issues/15
- [x] stackb/rules_proto#117: Possible cache issue on Bazel upgrade
- [x] stackb/rules_proto#118: Possible cache issue on Bazel upgrade
- [x] stackb/rules_proto#119: Resolved, aspect now used everywhere
- [x] stackb/rules_proto#120: Resolved
- [ ] stackb/rules_proto#121: Not tested
- [ ] stackb/rules_proto#122: Not tested
- [x] stackb/rules_proto#123: No relevant
- [ ] stackb/rules_proto#127: Pending work in https://github.com/rules-proto-grpc/rules_proto_grpc/issues/22
